---
- name: Instalação do Docker
  hosts: all
  become: true
  tasks:
    - name: Atualizar cache de pacotes
      apt:
        update_cache: yes
    - name: Instalar dependências do Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present
    - name: Permissão Diretorio keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
    - name: Atualizar cache de pacotes (novamente)
      apt:
        update_cache: yes
    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
    - name: Instalar Docker Compose
      shell: |
        curl -sSL https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash
        creates: /usr/local/bin/docker-compose
    - name: Adicionar usuário ao grupo docker
      user:
        name: vagrant
        groups: docker
        append: yes
    - name: Reiniciar serviço do Docker
      service:
        name: docker
        state: restarted
